
par(mfrow=c(4,4))
plot(attribute.rating$Person, attribute.rating$crunchy, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$creamy, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$sweet, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$chocolaty, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$healthful, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$calorie, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$rich, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$addiction, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$accessible, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$handy, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$wrapping, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$Person, attribute.rating$image, col=hcl, pch=19, cex=0.5)
plot(attribute.rating$, attribute.rating$commercial, col=hcl, pch=19, cex=0.5)
